In [1]:
import torch
from einops import rearrange
from einops.layers.torch import Rearrange

# 创建一个示例输入：5 张 3通道、28x28 的图像
x = torch.randn(5, 3, 28, 28)
print("原始输入 shape:", x.shape)
# 输出: torch.Size([5, 3, 28, 28])

原始输入 shape: torch.Size([5, 3, 28, 28])


In [2]:
import torch
import torch.nn as nn

# 创建一个 ReLU 层
relu = nn.ReLU()

# 创建一个包含负值和正值的随机张量作为输入
input_tensor = torch.randn((2, 3))

# 应用 ReLU 函数
output_tensor = relu(input_tensor)

print("Input tensor:\n", input_tensor)
print("Output tensor after applying ReLU:\n", output_tensor)

Input tensor:
 tensor([[-1.8402,  0.3847, -0.8930],
        [-0.5467, -0.3358, -0.6392]])
Output tensor after applying ReLU:
 tensor([[0.0000, 0.3847, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [11]:
import torch as t
t.__version__
a=t.Tensor(2,3)
print(a)
b=t.Tensor([[1,2,3],[4,5,6]])
b
b.tolist()
b
c=t.Tensor(t.rand(2,3))
c

t.ones(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
import torch as t
a=t.arange(6).view(2,3)
a
t.cat((a,a),0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [26]:
import torch as t
mask=t.arange(6).view(2,3)
print(mask)
print(mask.transpose(0,1))

print(mask.view(3,2))


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [30]:
import torch as t
a=t.randn(3,4,requires_grad=True)
a.requires_grad

b=t.zeros(3,4).requires_grad_()
c=(a+b).sum()
c.backward()
c
a.is_leaf,b.is_leaf,c.is_leaf

(True, True, False)

In [40]:
import torch as t
from torch import nn

class Linear(nn.Module):
    def __init__(self,in_features,out_features):
        super().__init__()
        self.W=nn.Parameter(t.randn(in_features,out_features))
        self.b=nn.Parameter(t.randn(out_features))

    def forward(self,x):
        x=x.mm(self.W)
        return x+self.b.expand_as(x)

layer=Linear(4,3)
input=t.randn(2,4)
print(input)
output=layer(input)
print(output)

for name,parameter in layer.named_parameters():
    print(name,parameter)

tensor([[-0.8662,  0.8815,  0.6420, -1.2151],
        [ 0.3977, -1.6876, -1.1811,  1.3496]])
tensor([[ 1.2899, -1.0383,  1.9392],
        [-0.7592, -4.0119, -1.4248]], grad_fn=<AddBackward0>)
W Parameter containing:
tensor([[ 2.0096, -0.3451, -0.8031],
        [-0.0127, -0.1022,  0.5106],
        [ 0.8477, -0.4706, -1.0869],
        [-1.1995, -1.4262, -1.1770]], requires_grad=True)
b Parameter containing:
tensor([ 1.0403, -2.6780,  0.0611], requires_grad=True)


In [41]:
import torch as t
from torch import nn

input=t.randint(10,(1,1,4,4))
print(input)

pool=nn.AvgPool2d(2,2)
pool(input)

tensor([[[[9, 4, 3, 4],
          [0, 2, 6, 9],
          [1, 8, 5, 2],
          [3, 0, 2, 0]]]])


tensor([[[[3, 5],
          [3, 2]]]])

In [43]:
import torch as t
from torch import nn
input=t.randn(2,3)
print(input)
linear=nn.Linear(3,4)
h=linear(input)
h

tensor([[-1.1798, -0.6617,  0.8140],
        [ 0.0497, -0.3220,  0.7638]])


tensor([[ 0.9086, -1.4717,  0.2016, -0.0185],
        [ 0.6468, -0.7616, -0.0914,  0.2499]], grad_fn=<AddmmBackward0>)

In [51]:
import torch as t
from torch import nn

bn=nn.BatchNorm1d(4)
bn.weight.data=t.ones(4)*4
bn.bias.data=t.zeros(4)
bn_out=bn(h)
bn_out
bn_out.mean(0),bn_out.std(0,unbiased=False)


dropout=nn.Dropout(0.5)
o=dropout(bn_out)
o

tensor([[ 7.9977, -0.0000,  0.0000, -7.9978],
        [-7.9977,  7.9997, -0.0000,  7.9978]], grad_fn=<MulBackward0>)

In [53]:
import torch as t
from torch import nn

t.manual_seed(2021)
input=t.randn(2,3,4).float()
lstm=nn.LSTM(4,3,1)
h0=t.randn(1,3,3)
c0=t.randn(1,3,3)
out1,hn=lstm(input,(h0,c0))
out1.shape

torch.Size([2, 3, 3])

In [56]:
import torch as t
from torch import nn

score=t.randn(3,2)
print(score)
label=t.Tensor([1,0,1]).long()

print(label)

criterion=nn.CrossEntropyLoss()
loss=criterion(score,label)
loss

tensor([[-0.9744,  1.1170],
        [-1.1003,  0.2106],
        [-0.0648, -1.3755]])
tensor([1, 0, 1])


tensor(1.0718)

In [63]:
import torch as t
from torch import nn

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.param1=nn.Parameter(t.rand(3,3))
        self.submodel1=nn.Linear(3,4)

    def forward(self,input):
        x=self.param1.mm(input)
        x=self.submodel1(x)
        return x

net=Net()
net
net._modules
net._parameters
net.param1

for name,param in net.named_parameters():
    print(name,param)

param1 Parameter containing:
tensor([[0.7363, 0.2989, 0.0405],
        [0.3402, 0.5186, 0.7003],
        [0.0576, 0.2705, 0.7573]], requires_grad=True)
submodel1.weight Parameter containing:
tensor([[-0.1223,  0.4186, -0.5044],
        [ 0.3180, -0.1134, -0.2424],
        [ 0.0792,  0.1042, -0.2172],
        [ 0.4282, -0.1772,  0.0880]], requires_grad=True)
submodel1.bias Parameter containing:
tensor([-0.4514, -0.1639,  0.5011,  0.0141], requires_grad=True)


In [66]:
import torch as t
from torch import nn

input=t.arange(0,12).view(3,4).float()
model=nn.Dropout()
model(input)
model.training=False
model(input)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [77]:
from einops import rearrange,reduce
a=t.rand(16,3,64,64)
# rearrange(a,'b c h w -> b h w c').shape
y=rearrange(a,'b c h w -> b (h w c)')
print(y)

tensor([[0.4289, 0.8754, 0.0754,  ..., 0.8345, 0.0797, 0.5282],
        [0.0242, 0.1685, 0.3807,  ..., 0.8645, 0.2177, 0.6137],
        [0.2852, 0.6471, 0.4459,  ..., 0.1612, 0.7376, 0.9609],
        ...,
        [0.4720, 0.3116, 0.6044,  ..., 0.6558, 0.7311, 0.5558],
        [0.4924, 0.2270, 0.1743,  ..., 0.7084, 0.4477, 0.4235],
        [0.9274, 0.7480, 0.5455,  ..., 0.0854, 0.5966, 0.5046]])


In [74]:
import torch as t
from einops import rearrange

# 创建一个非常小的张量：1张图片，2个通道，2x2 大小
a = t.tensor([
    [[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]
])  # 形状是 (2, 2, 2)

print("原始张量 a:")
print(a)
output = rearrange(a, 'c h w -> h w c')
print("rearrange 后的结果:")
print(output)



原始张量 a:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
rearrange 后的结果:
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [79]:
import torch as t
from einops import rearrange,reduce
img=t.randn(1,3,256,256)
x=rearrange(img,'b c (h p1) (w p2) -> b (p1 p2) (h w c)',p1=8,p2=8)
x.shape


torch.Size([1, 64, 3072])